[package]
name = "lox-in-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4"
chrono =  "0.4"
serde_json = "1.0"
serde = { version = "1.0.217", features = ["derive"] }
dyn-clone = "1.0.17"
